### ISSUE TITLE
启用端口撒的文档全是 错的

### ISSUE THREAD

**Issue by bluekevin** [givebest/webpack-multiple-entry#3]
访问路径也不对，无法正常启动查看

**Comment by givebest** [comment]
@bluekevin  能描述清楚些吗？

我猜是不是端口冲突了？可以在 `config/webpack.config.js` 里 213 行修改为别的试下：
```js
	port: 8080,
```

**Comment by EmptyCharles** [comment]
![image](https://user-images.githubusercontent.com/13376763/38973330-df9d69e6-43d7-11e8-8f27-95b031ed80cb.png)
编译路径有问题

**Comment by givebest** [comment]
@EmptyCharles  已修复
